#!/usr/bin/env sh
CMDZ="$1"
PROCNM="kiabluejay"

skillo() {
  pkill $PROCNM && pgrep $PROCNM && pkill -9 $PROCNM
}

if [ "$CMDZ" == "start" ]; then
  pgrep $PROCNM || cd /home/crab/ && /home/crab/$PROCNM > /home/crab/logs/web.log 2>&1 &
fi
if [ "$CMDZ" == "restart" ]; then
  skillo && cd /home/crab/ && /home/crab/$PROCNM > /home/crab/logs/web.log 2>&1 &
fi
if [ "$CMDZ" == "stop" ]; then
  skillo
fi
