#!/usr/bin/env sh
CMDZ="$1"
PROCNM="kiagateway_https"
PROCNMCMD="/opt/kiagateway/bin/kiagateway_https /opt/kiagateway/etc/config.toml"

skillo() {
  pkill $PROCNM || pgrep $PROCNM && pkill -9 $PROCNM
}

if [ "$CMDZ" == "start" ]; then
  pgrep $PROCNM || $PROCNMCMD > /var/log/gate.out 2>&1 &
fi
if [ "$CMDZ" == "restart" ]; then
  skillo
  $PROCNMCMD > /var/log/gate.out 2>&1 &
fi
if [ "$CMDZ" == "stop" ]; then
  skillo
fi
