#!/usr/bin/env sh
CMDZ="$1"
PROCNM="kiaproxy2"

skillo() {
  pkill $PROCNM && pgrep $PROCNM && pkill -9 $PROCNM
}

if [ "$CMDZ" == "start" ]; then  
  pgrep $PROCNM || export SERVERS=127.0.0.1:3003 && cd /root && /root/kiaproxy2 > /var/log/kiaproxy2.log 2>&1 &
fi
if [ "$CMDZ" == "restart" ]; then
  skillo && export SERVERS=127.0.0.1:3003 && cd /root && /root/kiaproxy2 > /var/log/kiaproxy2.log 2>&1 &
fi
if [ "$CMDZ" == "stop" ]; then
  skillo
fi
