#!/usr/bin/env sh
CMDZ="$1"
PROCNM="redirectrix2"

skillo() {
  pkill $PROCNM && pgrep $PROCNM && pkill -9 $PROCNM
}

if [ "$CMDZ" == "start" ]; then
  pgrep $PROCNM || /root/$PROCNM > /dev/null 2>&1 &
fi
if [ "$CMDZ" == "restart" ]; then
  skillo && pgrep $PROCNM || /root/$PROCNM > /dev/null 2>&1 &
fi
if [ "$CMDZ" == "stop" ]; then
  skillo
fi
